# Q1 What are the different data structures used in Tensorflow?. Give some examples


Different Data Structures in TensorFlow:

Tensor:

The fundamental data structure in TensorFlow is a tensor, a multi-dimensional array.
Example:

import tensorflow as tf
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
Variable:

A special type of tensor that can be modified after it's created. Useful for representing trainable parameters in a model.
Example:

import tensorflow as tf
variable = tf.Variable([1, 2, 3])
Placeholder:

Used to feed actual training examples.
Example:

import tensorflow as tf
placeholder = tf.placeholder(tf.float32, shape=(None, 3))
SparseTensor:

Efficiently represents tensors with a large number of zero values.
Example:

import tensorflow as tf
indices = tf.constant([[0, 1], [2, 3]])
values = tf.constant([1, 2])
shape = tf.constant([3, 4])
sparse_tensor = tf.sparse.SparseTensor(indices, values, shape)

# Q2 How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example

TensorFlow Constant vs. Variable:

Constant:

Created using tf.constant.
Cannot be modified after creation.
Example:

import tensorflow as tf
constant_tensor = tf.constant([1, 2, 3])
Variable:

Created using tf.Variable.
Can be modified using operations like assign.
Example:

import tensorflow as tf
variable = tf.Variable([1, 2, 3])
updated_variable = variable.assign([4, 5, 6])

# Q3 Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow.

Matrix Addition, Multiplication, and Element-Wise Operations in TensorFlow:

Matrix Addition:


import tensorflow as tf
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
result = tf.add(matrix_a, matrix_b)
Matrix Multiplication:

import tensorflow as tf
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
result = tf.matmul(matrix_a, matrix_b)
Element-Wise Operations:


import tensorflow as tf
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Element-wise multiplication
elementwise_mul = tf.multiply(matrix_a, matrix_b)

# Element-wise addition
elementwise_add = tf.add(matrix_a, matrix_b)

# Element-wise division
elementwise_div = tf.divide(matrix_a, matrix_b)

In [1]:
pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.2/475.2 MB 3.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 76.1 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 55.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 47.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 75.3 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 12.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 13.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 64.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 22.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 70.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 74.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 9.3 MB/s eta 0:00:

# Q1 Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix Ac

In [2]:
import tensorflow as tf

2023-11-23 05:18:35.915089: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-23 05:18:35.980143: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-23 05:18:35.980201: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-23 05:18:35.981678: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-23 05:18:35.990881: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-23 05:18:35.991693: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [8]:
matrix_A = tf.random.normal(shape=(2,2))
print(matrix_A)

tf.Tensor(
[[ 0.43190148  0.55711144]
 [-0.34909406 -0.14047505]], shape=(2, 2), dtype=float32)


# Q2 Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display the values of matrix Bc

In [16]:

matrix_B = tf.random.truncated_normal(shape=(4,4))
print(matrix_B)

tf.Tensor(
[[ 0.8473109  -0.59422064  1.418043    0.29948193]
 [ 1.3395176  -0.03460002  0.28524068 -1.4633784 ]
 [-0.42170304 -0.34477264 -0.76952714  1.8646321 ]
 [ 0.74793893 -1.1916194  -0.45692664  0.18311708]], shape=(4, 4), dtype=float32)


# Q3 Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix Cc

In [20]:
matrix_C =  tf.random.normal(shape=(2,2),mean=2,stddev=0.5)
print(matrix_C)

tf.Tensor(
[[1.2698538 1.2102458]
 [1.780852  1.8892804]], shape=(2, 2), dtype=float32)


# Q 4Perform matrix addition between matrix A and matrix B, and store the result in matrix D

In [24]:
matrix_A = tf.random.normal(shape=(2,2))

matrix_B = tf.random.truncated_normal(shape=(2,2))

matrix_d = tf.add(matrix_A,matrix_B)
print(matrix_d)


tf.Tensor(
[[ 0.92457044 -2.4201722 ]
 [-0.8395164  -1.2449152 ]], shape=(2, 2), dtype=float32)


# Q5 Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [28]:
matrix_E = tf.multiply(matrix_C,matrix_d)
print(matrix_E)

tf.Tensor(
[[ 1.1740693 -2.9290035]
 [-1.4950545 -2.351994 ]], shape=(2, 2), dtype=float32)


# Q1Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform functionc

In [30]:
matrix_f = tf.random.uniform(shape=(2,2))
print(matrix_f)

tf.Tensor(
[[0.18114603 0.47209382]
 [0.8193742  0.0070858 ]], shape=(2, 2), dtype=float32)


# Q2 Calculate the transpose of matrix F and store the result in matrix Gc

In [32]:
matrix_G = tf.transpose(matrix_f)
print(matrix_G)

tf.Tensor(
[[0.18114603 0.8193742 ]
 [0.47209382 0.0070858 ]], shape=(2, 2), dtype=float32)


# Q3 Calculate the elementwise exponential of matrix F and store the result in matrix H

In [34]:
matrix_h = tf.exp(matrix_f)
print(matrix_h)

tf.Tensor(
[[1.1985902 1.6033478]
 [2.2690794 1.007111 ]], shape=(2, 2), dtype=float32)


# Q4 Create a matrix I by concatenating matrix F and matrix G horizontally

In [35]:
matrix_l = tf.concat(matrix_f,matrix_G)

ValueError: concat_dim: Tensor conversion requested dtype int32 for Tensor with dtype float32: <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.18114603, 0.8193742 ],
       [0.47209382, 0.0070858 ]], dtype=float32)>

# Q5 Create a matrix J by concatenating matrix F and matrix H vertically.